name: docker-vscode
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=2.0.2
  - pandas=2.3.1
  - conda-lock=3.0.4
platforms:
  - linux-aarch64
  - linux-64
  - osx-arm64
  - osx-64
  - win-64
